### ISSUE TITLE
Submodel example does not work on python 3.11

### ISSUE THREAD

**Issue by FrankDrop** [Dronakurl/nicecrud#1]
Using python 3.11 and running the submodel.py example, I get the following error:

```txt
Traceback (most recent call last):
  File "/workspaces/mpmca-web/frontend/submodel.py", line 23, in gui
    if context and context.get("gui"):
                   ^^^^^^^^^^^
AttributeError: 'property' object has no attribute 'get'. Did you mean: 'fget'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/mpmca-web/frontend/submodel.py", line 45, in <module>
    crud_app = NiceCRUD(basemodels=[actress, another_actress], config=crud_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/mpmca-web/.venv/lib/python3.11/site-packages/niceguicrud/nicecrud.py", line 455, in __init__
    self.create_rows_and_cols()
  File "/workspaces/mpmca-web/.venv/lib/python3.11/site-packages/niceguicrud/nicecrud.py", line 549, in create_rows_and_cols
    rows, columns = basemodellist_to_rows_and_cols(self.basemodels)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/mpmca-web/.venv/lib/python3.11/site-packages/niceguicrud/basemodel_to_table.py", line 56, in basemodellist_to_rows_and_cols
    rows = basemodellist_to_rows(bmlist, exclude, include)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/mpmca-web/.venv/lib/python3.11/site-packages/niceguicrud/basemodel_to_table.py", line 43, in basemodellist_to_rows
    rr = bm.model_dump(include=include, exclude=exclude, context=dict(gui=True))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/mpmca-web/.venv/lib/python3.11/site-packages/pydantic/main.py", line 364, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `gui`: AttributeError: 'property' object has no attribute 'get'
```

**Comment by Dronakurl** [comment]
Thanks for opening an issue! I will look into it tonight.

Frank Drop ***@***.***> schrieb am Fr. 26. Juli 2024 um 12:07:
